---
- name: Install common packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes
