---
- name: Common setup on all nodes
  hosts: all
  become: yes
  roles:
    - common

- name: Kubernetes master setup
  hosts: master
  become: yes
  roles:
    - master

- name: Kubernetes worker setup
  hosts: worker
  become: yes
  roles:
    - worker
