---
- name: Initialize Kubernetes Master
  shell: |
    kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf

- name: Setup kubeconfig for ec2-user
  shell: |
    mkdir -p /home/ec2-user/.kube
    cp -i /etc/kubernetes/admin.conf /home/ec2-user/.kube/config
    chown ec2-user:ec2-user /home/ec2-user/.kube/config

- name: Install Flannel CNI
  become: yes
  become_user: ec2-user
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Extract kubeadm join command
  shell: kubeadm token create --print-join-command
  register: join_cmd

- name: Set join command fact
  set_fact:
    join_command: "{{ join_cmd.stdout }}"
